import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pay",
  description: "Generated by create next app",
};
export default function PayLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return <section className="p-5">{children}</section>;
}
